# Generated by Django 5.0.6 on 2024-07-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="license_plate_image",
            field=models.ImageField(
                default=None, null=True, upload_to="License_plate_images/"
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="vehicle_image",
            field=models.ImageField(
                default=None, null=True, upload_to="Vehicle_images/"
            ),
        ),
    ]
