# Generated by Django 5.0.6 on 2024-07-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0002_record_license_plate_image_record_vehicle_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="license_plate_image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="License_plate_images/"
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="vehicle_image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="Vehicle_images/"
            ),
        ),
    ]
