# Generated by Django 4.2 on 2025-05-22 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_record_license_plate_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='licenseplate_no',
            new_name='liscenseplate_no',
        ),
    ]
