# Generated by Django 4.2 on 2025-05-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_rename_licenseplate_no_record_liscenseplate_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='liscenseplate_no',
            new_name='licenseplate_no',
        ),
    ]
