# Generated by Django 4.2 on 2025-05-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_rename_liscenseplate_no_record_licenseplate_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicensePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vehicle_image', models.ImageField(blank=True, null=True, upload_to='plates/')),
            ],
        ),
    ]
