# Generated by Django 4.2 on 2025-06-04 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='detection_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='record',
            name='direction',
            field=models.CharField(blank=True, default='unknown', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='location',
            field=models.CharField(blank=True, default='unknown', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='max_speed',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='plate_detection_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='vehicle_type',
            field=models.CharField(blank=True, default='unknown', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='record',
            name='licenseplate_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
